apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-oiib
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-oiib
    app.kubernetes.io/part-of: test-rhtap-57-app
  name: devfile-sample-code-with-quarkus-oiib
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-oiib
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-oiib
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-57-tenant/test-rhtap-57-app/devfile-sample-code-with-quarkus-oiib@sha256:062d9e13f8b0bc4338b144f2889df62b0725f6848b2e0b40803075bd6e2afec1
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
